name: Nightly Builds

on:
  push:
    branches:
      - 'release/**'
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/my-build-action.yml
    with:
      name: 'Nightly Builds'
    secrets: inherit
  build_minified_release:
    uses: ./.github/workflows/my-build-action.yml
    with:
      name: 'Minified Builds'
      minify: true
    secrets: inherit
