name: Nightly Builds

on:
  push:
    branches:
      - 'release/**'
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/my-build-action.yml
        with:
          name: 'Nightly Builds'
  build_minified_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/my-build-action.yml
        with:
          name: 'Minified Builds'
        env:
          CI_BUILD_MINIFY: true
