name: Release

on:
  push:
    branches:
      - 'release/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        # Set Current Date As Env Variable
        - name: Build App
          uses: build.yml

        - name: Get tag name
          id: tag_name
          run: echo ::set-output name=tag_name::${GITHUB_REF/refs\/tags\//}
